console.log('Importing express...');
import express from 'express';
console.log('Importing cors...');
import cors from 'cors';
console.log('Importing mongoose...');
import mongoose from 'mongoose';
console.log('Importing passport...');
import passport from 'passport';
console.log('Importing passport-google-oauth20...');
import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
console.log('Importing express-session...');
import session from 'express-session';
console.log('Importing jsonwebtoken...');
import jwt from 'jsonwebtoken';
console.log('Importing cookie-parser...');
import cookieParser from 'cookie-parser';
console.log('Importing dotenv...');
import dotenv from 'dotenv';
console.log('Importing bcryptjs...');
import bcrypt from 'bcryptjs';
console.log('All imports done!');
